
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo-helm-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-demo-helm-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-demo-helm-app
    spec:
      containers:
        - name: {{ .Release.Name }}-demo-helm-container
          image: {{ .Values.demoHelm.image.repository }}:{{ .Values.demoHelm.image.tag }}
          imagePullPolicy: {{ .Values.demoHelm.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ include "my-demo-helm.fullMySQLConnectionURL" . | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-username
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-password
                  key: password
