apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-helm-service
spec:
  selector:
    app: {{ .Release.Name }}-demo-helm-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer